
name: authenticator
#fullname:
replicacounts: 2

images:
  PullSecrets: my-secret
  repository: harbor/my/image
  tag: latest

config:
  configmaps: conf1, conf2

ingress:
  enabled: True
  hosts:
  - host: /auth
    paths:
    - path: /auth
        service: auth
        port: 3000

    - path: /auth2
        service: auth
        port: 3000

service:
  type: ClusterIP
  ports: 