
name: q
#fullname:
replicacounts: 1

images:
  PullSecrets: q
  repository: q
  tag: latest

config:
  configmaps: []
  env:
  - name: MESSAGE
    value: 'did work'

service:
  type: ClusterIP

ingress:
  enabled: True
  hosts:
  - host: test
    paths:
      - path: path
        service: shit
        port: 3000
    
service:
  type: ClusterIP
  ports:
  - name: my service
    port: my port
    
service:
  type: ClusterIP
  ports:
  - name: 1
    port: 1
    